enum ObjectCategory {
    "not a ride",
    "transport", // 0
    "gentle",
    "rollercoaster",
    "thrill",
    "water",
    "shop", //5
    "scenery"
}
enum ScenarioName {
    "forest frontiers",//0
    "dynamite dunes",
    "leafy lake",
    "diamond heights",
    "evergreen gardens",
    "bumbly beach",
    "trinity islands",
    "katie’s world",
    "dinky park",
    "aqua park",
    "millennium mines",
    "karts & coasters",
    "mel’s world",
    "mothball mountain",
    "pacific pyramids",
    "crumbly woods",
    "big pier",
    "lightning peaks",
    "ivory towers",
    "rainbow valley",
    "thunder rock",
    "mega park",
    "whispering cliffs",
    "three monkeys park",
    "canary mines",
    "barony bridge",
    "funtopia",
    "haunted harbor",
    "fun fortress",
    "future world",
    "gentle glen",
    "jolly jungle",
    "hydro hills",
    "sprightly park",
    "magic quarters",
    "fruit farm",
    "butterfly dam",
    "coaster canyon",
    "thunderstorm park",
    "harmonic hills",
    "roman village",
    "swamp cove",
    "adrenaline heights",
    "utopia park",
    "rotting heights",
    "fiasco forest",
    "pickle park",
    "giggle downs",
    "mineral park",
    "coaster crazy",
    "urban park",
    "geoffery gardens",
    "iceberg islands",
    "volcania",
    "arid heights",
    "razor rocks",
    "crater lake",
    "vertigo views",
    "big pier 2",
    "dragon’s cove",
    "good knight park",
    "wacky warren",
    "grand glacier",
    "crazy craters",
    "dusty desert",
    "woodworm park",
    "icarus park",
    "sunny swamps",
    "frightmare hills",
    "thunder rocks",
    "octagon park",
    "pleasure island",
    "icicle worlds",
    "southern sands",
    "tiny towers",
    "nevermore park",
    "pacifica",
    "urban jungle",
    "terror town",
    "megaworld park",
    "venus ponds",
    "micro park",
    "electric fields",
    "factory capers",
    "crazy castle",
    "dusty greens",
    "bumbly bazaar",
    "infernal views",
    "lucky lake",
    "botany breakers",
    "alpine adventures",
    "gravity gardens",
    "extreme heights",
    "amity airfield",
    "ghost town",
    "fungus woods",
    "rainbow summit",
    "over the edge",
    "great wall of china",
    "canyon calamities",
    "sugarloaf shores",
    "mines of africa",
    "park maharaja",
    "ayers adventure",
    "european extravaganza",
    "rollercoaster heaven",
    "lost city founder",
    "mirage madness",
    "icy adventures",
    "okinawa coast",
    "beach barbecue blast",
    "from the ashes",
    "wacky waikiki",
    "rainforest romp",
    "sherwood forest",
    "crater carnage",
    "alcatraz",
    "woodstock",
    "cliffside castle",
    "extraterrestrial extravaganza",
    "animatronic antics",
    "coastersaurus",
    "schneider shores",
    "gemini city",
    "mythological madness",
    "rocky rambles",
    "metropolis",
    "rock ‘n’ roll revival",
    "alton towers",
    "blackpool pleasure beach",
    "heide-park",
    "six flags belgium",
    "six flags great adventure",
    "six flags holland",
    "six flags magic mountain",
    "six flags over texas",
    "fort anachronism",
    "build your own six flags belgium",
    "build your own six flags great adventure",
    "build your own six flags holland",
    "build your own six flags magic mountain",
    "build your own six flags park",
    "build your own six flags over texas",
    "random RCT1",
    "random loopy landscapes",
    "random corkscrew follies",
    "random RCT2",
    "random wacky worlds",
    "random time twister",
    "random RCT1 expansions",
    "random RCT2 expansions",
    "archipelago madness (vanilla)",
    "archipelago madness (expansions)"

}
// var reverseScenarioName = new Map<string, ScenarioName>();
// Object.keys(ScenarioName).forEach((scenarioName: ScenarioName) => {
//     const scenarioNameValue: string = ScenarioName[scenarioName as any];
//     reverseScenarioName.set(scenarioNameValue, scenarioName);
// });
