enum ObjectCategory {
    "not a ride",
    "transport", // 0
    "gentle",
    "rollercoaster",
    "thrill",
    "water",
    "shop", //5
    "scenery"
}
enum ScenarioName {
    "forest frontiers",//0
    "dynamite dunes",
    "leafy lake",
    "diamond heights",
    "evergreen gardens",
    "bumbly beach",
    "trinity islands",
    "katie’s world",
    "dinky park",
    "aqua park",
    "millennium mines",
    "karts and coasters",
    "mel’s world",
    "mothball mountain",
    "pacific pyramids",
    "crumbly woods",
    "big pier",
    "lightning peaks",
    "ivory towers",
    "rainbow valley",
    "thunder rock",
    "mega park",
    "whispering cliffs",
    "three monkeys park",
    "canary mines",
    "barony bridge",
    "funtopia",
    "haunted harbor",
    "fun fortress",
    "future world",
    "gentle glen",
    "jolly jungle",
    "hydro hills",
    "sprightly park",
    "magic quarters",
    "fruit farm",
    "butterfly dam",
    "coaster canyon",
    "thunderstorm park",
    "harmonic hills",
    "roman village",
    "swamp cove",
    "adrenaline heights",
    "utopia park",
    "rotting heights",
    "fiasco forest",
    "pickle park",
    "giggle downs",
    "mineral park",
    "coaster crazy",
    "urban park",
    "geoffery gardens",
    "iceberg islands",
    "volcania",
    "arid heights",
    "razor rocks",
    "crater lake",
    "vertigo views",
    "big pier 2",
    "dragon’s cove",
    "good knight park",
    "wacky warren",
    "grand glacier",
    "crazy craters",
    "dusty desert",
    "woodworm park",
    "icarus park",
    "sunny swamps",
    "frightmare hills",
    "thunder rocks",
    "octagon park",
    "pleasure island",
    "icicle worlds",
    "southern sands",
    "tiny towers",
    "nevermore park",
    "pacifica",
    "urban jungle",
    "terror town",
    "megaworld park",
    "venus ponds",
    "micro park",
    "electric fields",
    "factory capers",
    "crazy castle",
    "dusty greens",
    "bumbly bazzar",
    "infernal views",
    "lucky lake",
    "botany breakers",
    "alpine adventures",
    "gravity gardens",
    "extreme heights",
    "amity airfield",
    "ghost town",
    "fungus woods",
    "rainbow summit",
    "africa - victoria falls",
    "asia - great wall of china tourism enhancement",
    "north - america grand canyon",
    "south - america rio carnival",
    "africa - african diamond mine",
    "asia - maharaja palace",
    "australasia - ayers rock",
    "europe - european cultural festival",
    "north america - rollercoaster heaven",
    "south america - inca lost city",
    "africa - oasis",
    "antartic - ecological salvage",
    "asia - japanese costal reclaim",
    "australasia - fun at the beach",
    "europe - renovation",
    "n. america - extreme hawaiian island",
    "south america - rain forest plateau",
    "dark age - robin hood",
    "prehistoric - after the asteroid",
    "roaring twenties - prison island",
    "rock ’n’ roll - flower power",
    "dark age - castle",
    "future - first encounters",
    "mythological - animatronic film set",
    "prehistoric - jurassic safari",
    "roaring twenties - schnider cup",
    "future - future world",
    "mythological - cradle of civilization",
    "prehistoric - stone age",
    "roaring twenties - skyscrapers",
    "rock ’n’ roll - rock ’n’ roll",
    "alton towers",
    "blackpool pleasure beach",
    "heide-park",
    "six flags belgium",
    "six flags great adventure",
    "six flags holland",
    "six flags magic mountain",
    "six flags over texas",
    "fort anachronism",
    "build your own six flags belgium",
    "build your own six flags great adventure",
    "build your own six flags holland",
    "build your own six flags magic mountain",
    "build your own six flags park",
    "build your own six flags over texas",
}
// var reverseScenarioName = new Map<string, ScenarioName>();
// Object.keys(ScenarioName).forEach((scenarioName: ScenarioName) => {
//     const scenarioNameValue: string = ScenarioName[scenarioName as any];
//     reverseScenarioName.set(scenarioNameValue, scenarioName);
// });