/* eslint-disable camelcase */
// eslint-disable-next-line import/prefer-default-export
enum RideType {
    "Spiral Roller Coaster", // 0
    "Stand Up Roller Coaster",
    "Suspended Swinging Coaster",
    "Inverted Roller Coaster",
    "Junior Roller Coaster",
    "Miniature Railway",
    "Monorail",
    "Mini Suspended Roller Coaster",
    "Boat Hire",
    "Wooden Wild Mouse",
    "Steeplechase", // 10
    "Car Ride",
    "Launched Freefall",
    "Bobsleigh Coaster",
    "Observation Tower",
    "Looping Roller Coaster",
    "Dinghy Slide",
    "Mine Train Coaster",
    "Chairlift",
    "Corkscrew Roller Coaster",
    "Maze", // 20
    "Spiral Slide",
    "Go Karts",
    "Log Flume",
    "River Rapids",
    "Dodgems",
    "Swinging Ship",
    "Swinging Inverter Ship",
    "Food Stall",
    "1d",
    "Drink Stall", // 30
    "1f",
    "Shop",
    "Merry Go Round",
    "22 ",
    "Information Kiosk",
    "Toilets",
    "Ferris Wheel",
    "Motion Simulator",
    "3d Cinema",
    "Top Spin", // 40
    "Space Rings",
    "Reverse Freefall Coaster",
    "Lift",
    "Vertical Drop Roller Coaster",
    "Cash Machine",
    "Twist",
    "Haunted House",
    "First Aid",
    "Circus",
    "Ghost Train", // 50
    "Twister Roller Coaster",
    "Wooden Roller Coaster",
    "Side Friction Roller Coaster",
    "Steel Wild Mouse",
    "Multidimension Roller Coaster",
    "Multidimension Roller Coaster (alt)",
    "Flying Roller Coaster",
    "Flying Roller Coaster (alt)",
    "Virginia Reel",
    "Splash Boats", // 60
    "Mini Helicopters",
    "Lay Down Roller Coaster",
    "Suspended Monorail",
    "Lay Down Roller Coaster (alt)",
    "Reverser Roller Coaster",
    "Heartline Twister Coaster",
    "Mini Golf",
    "Giga Coaster",
    "Roto Drop",
    "Flying Saucers", // 70
    "Crooked House",
    "Monorail Cycles",
    "Compact Inverted Coaster",
    "Water Coaster",
    "Air Powered Vertical Coaster",
    "Inverted Hairpin Coaster",
    "Magic Carpet",
    "Submarine Ride",
    "River Rafts",
    "Type 50", // 80
    "Enterprise",
    "52 ",
    "53 ",
    "54 ",
    "55 ",
    "Inverted Impulse Coaster",
    "Mini Roller Coaster",
    "Mine Ride",
    "59 ",
    "LIM Launched Roller Coaster", //  90
    "Hypercoaster",
    "Hypertwister",
    "Monster Trucks",
    "Spinning Wild Mouse",
    "Classic Mini Roller Coaster",
    "Hybrid Coaster",
    "Single Rail Roller Coaster"
}
