name: release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        RELEASE_TAG: testing
    defaults:
      run:
        # Must be explicit for proper pipefail support
        shell: bash
    steps:
    # set the tag to the current ref, otherwise stick with the testing tag
    - if: ${{ ! startsWith(github.ref, 'refs/heads/') }}
      run: echo "RELEASE_TAG=${{ github.ref }}" >> $GITHUB_ENV
      shell: bash

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }}
    - name: Aquire openrct2.d.ts
      run: |
        mkdir lib
        curl -Lo lib/openrct2.d.ts https://github.com/OpenRCT2/OpenRCT2/raw/develop/distribution/openrct2.d.ts
    - name: Install
      run: npm install
    - name: Build
      run: npm run build-release
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "rollercoaster-tycoon-randomizer"
        path: out/rctrando.js
    - name: Upload Release Asset
      id: upload-release-asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: out/rctrando.js
        asset_name: rctrando.js
        tag: ${{ env.RELEASE_TAG }}
        overwrite: true
